# ---- Base ----
FROM node:22-slim AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# ---- Dependencies ----
FROM base AS deps
COPY package.json bun.lock ./
# Install bun for dependency resolution, then native build tools
RUN apt-get update && apt-get install -y python3 make g++ curl unzip && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"
RUN bun install --frozen-lockfile

# ---- Builder ----
FROM base AS builder
RUN apt-get update && apt-get install -y curl unzip && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build args → NEXT_PUBLIC_ env vars baked into the client bundle
ARG NEXT_PUBLIC_SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
ARG NEXT_PUBLIC_SOLANA_NETWORK=mainnet-beta
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SOLOMON_MINT
ARG NEXT_PUBLIC_SOLOMON_VAULT_PDA
ARG NEXT_PUBLIC_SOLOMON_USDC_ATA
ARG NEXT_PUBLIC_KAMINO_MINT
ARG NEXT_PUBLIC_KAMINO_VAULT_PDA
ARG NEXT_PUBLIC_KAMINO_USDC_ATA
ARG NEXT_PUBLIC_DRIFT_MINT
ARG NEXT_PUBLIC_DRIFT_VAULT_PDA
ARG NEXT_PUBLIC_DRIFT_USDC_ATA
ARG NEXT_PUBLIC_ORO_MINT
ARG NEXT_PUBLIC_ORO_VAULT_PDA
ARG NEXT_PUBLIC_ORO_USDC_ATA
ARG NEXT_PUBLIC_VAULT_AUTHORITY

ENV NEXT_PUBLIC_SOLANA_RPC_URL=$NEXT_PUBLIC_SOLANA_RPC_URL
ENV NEXT_PUBLIC_SOLANA_NETWORK=$NEXT_PUBLIC_SOLANA_NETWORK
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SOLOMON_MINT=$NEXT_PUBLIC_SOLOMON_MINT
ENV NEXT_PUBLIC_SOLOMON_VAULT_PDA=$NEXT_PUBLIC_SOLOMON_VAULT_PDA
ENV NEXT_PUBLIC_SOLOMON_USDC_ATA=$NEXT_PUBLIC_SOLOMON_USDC_ATA
ENV NEXT_PUBLIC_KAMINO_MINT=$NEXT_PUBLIC_KAMINO_MINT
ENV NEXT_PUBLIC_KAMINO_VAULT_PDA=$NEXT_PUBLIC_KAMINO_VAULT_PDA
ENV NEXT_PUBLIC_KAMINO_USDC_ATA=$NEXT_PUBLIC_KAMINO_USDC_ATA
ENV NEXT_PUBLIC_DRIFT_MINT=$NEXT_PUBLIC_DRIFT_MINT
ENV NEXT_PUBLIC_DRIFT_VAULT_PDA=$NEXT_PUBLIC_DRIFT_VAULT_PDA
ENV NEXT_PUBLIC_DRIFT_USDC_ATA=$NEXT_PUBLIC_DRIFT_USDC_ATA
ENV NEXT_PUBLIC_ORO_MINT=$NEXT_PUBLIC_ORO_MINT
ENV NEXT_PUBLIC_ORO_VAULT_PDA=$NEXT_PUBLIC_ORO_VAULT_PDA
ENV NEXT_PUBLIC_ORO_USDC_ATA=$NEXT_PUBLIC_ORO_USDC_ATA
ENV NEXT_PUBLIC_VAULT_AUTHORITY=$NEXT_PUBLIC_VAULT_AUTHORITY

# Webpack build (Turbopack uses too much RAM in containers)
RUN npx next build --webpack

# ---- Runner ----
FROM node:22-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 8080

CMD ["node", "server.js"]
