app = "foundation-app"
primary_region = "iad"

[build]
  [build.args]
    NEXT_PUBLIC_SOLANA_RPC_URL = "https://mainnet.helius-rpc.com/?api-key=5daea224-93bd-415d-ac58-9e5777656acf"
    NEXT_PUBLIC_SOLANA_NETWORK = "mainnet-beta"
    NEXT_PUBLIC_SUPABASE_URL = "https://vhjntobgqfvdyfqhovol.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Ghz6qzFVKglus_N-BhAaiA_Fn9fn6mv"
    NEXT_PUBLIC_SOLOMON_MINT = "HCT1A2bqswGk2z58HKnJrbYhMUNvUKgigrqWVEfqBs2R"
    NEXT_PUBLIC_SOLOMON_VAULT_PDA = "6Gc58dwDxSEGQ8VbVJbs7ZDfxDKAy2pBrVtPAtyQYXGD"
    NEXT_PUBLIC_SOLOMON_USDC_ATA = "tqGK2r5rTCA7Gnd3DK5wwDSkZ85Q3mt3JpFrXSSHesJ"
    NEXT_PUBLIC_KAMINO_MINT = "C6RBLzGSprxfKnXsPd2utGeGcvDvaTGYjPGWMx9HBDwm"
    NEXT_PUBLIC_KAMINO_VAULT_PDA = "83f5hSUBbYcu6JzX2Mg3bESvzA13esStfTB8tNXvdeLG"
    NEXT_PUBLIC_KAMINO_USDC_ATA = "Bn98q5ze7uxuepP2BBjhLh1LdLaGzX34HqiKF7eGiZE8"
    NEXT_PUBLIC_DRIFT_MINT = "AMu2EqRsidPmZAE3GbATmqfCz9EzPvHnsHxh5Nco3yUV"
    NEXT_PUBLIC_DRIFT_VAULT_PDA = "FwzXi18YZR3gWm9yC2ShBCDGy8iMf1pGdhKF14bPhDz7"
    NEXT_PUBLIC_DRIFT_USDC_ATA = "Hce9tZRNQdbndNdfa6B5C3WKr1a6PMVJmLkNSN3Rtq4X"
    NEXT_PUBLIC_ORO_MINT = "BQUvPX2FnAmg1DXhCE7oRheda59A8RVLRw3kM7quTj5W"
    NEXT_PUBLIC_ORO_VAULT_PDA = "GBKMkBVbJtWTuwhYR5mvSj4cQea64zM8pc7XsTpvFQeu"
    NEXT_PUBLIC_ORO_USDC_ATA = "8YquxRTEkN6w6eL9yYD63i9sPNQcVtHKfUbFhxUQjgiy"
    NEXT_PUBLIC_VAULT_AUTHORITY = "4J9mszyDLi4js4rh8Hq5spNaLCNt4fRozr781zcVBYgv"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"
    path = "/api/health"
    method = "GET"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
