[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fdn_vault_compute = "2PLMStk5P2GNKMH3ciK7N62wifwZZL9fmjcef4S7Ezop"
fdn_transfer_hook = "3hBtJLskNbhbdzjA8imqiR9uaWMKrvUEiwseenAwgCTs"

[programs.devnet]
fdn_vault_compute = "2PLMStk5P2GNKMH3ciK7N62wifwZZL9fmjcef4S7Ezop"
fdn_transfer_hook = "3hBtJLskNbhbdzjA8imqiR9uaWMKrvUEiwseenAwgCTs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet  = "../.keys_vaults/fdn_programs/deployer.json"

[scripts]
test = "bun run --cwd tests test"

[workspace]
members = [
    "fdn_vault_compute",
    "fdn_transfer_hook",
]
